# -*- coding: utf-8 -*-
from modules.compiler import Compiler

"""
Automatically generated by Colaboratory.
Original file is located at: https://colab.research.google.com/drive/1lE-s40-fYOnisOV0An43TE21aVHMCK0s
"""


tokens = Compiler.lexer(' 123.1321 + 4 *  56    ')
print(tokens)

# expected output:
# [(NUMBER 123), (PLUS +), (NUMBER 4), (TIMES *), (NUMBER 56), (END $)]